import type {
  CommitmentCode,
  CoverAssignmentSnapshot,
  CoverLoad,
  LunchAllocation,
  Person,
  SchoolPeriod,
  TeachingEvent,
  TimetableEntry,
} from "@/domain/timetable/types";

export const schoolPeriods: SchoolPeriod[] = [
  { id: "REG", label: "Registration", dayOrder: 0, startTime: "07:30", endTime: "07:55", coverRelevant: true },
  { id: "L1", label: "Lesson 1", dayOrder: 1, startTime: "07:55", endTime: "08:40", coverRelevant: true },
  { id: "L2", label: "Lesson 2", dayOrder: 2, startTime: "08:40", endTime: "09:25", coverRelevant: true },
  { id: "L3", label: "Lesson 3", dayOrder: 3, startTime: "09:25", endTime: "10:10", coverRelevant: true },
  { id: "BRK", label: "Break", dayOrder: 4, startTime: "10:10", endTime: "10:30", coverRelevant: false },
  { id: "L4", label: "Lesson 4", dayOrder: 5, startTime: "10:30", endTime: "11:15", coverRelevant: true },
  { id: "L5", label: "Lesson 5", dayOrder: 6, startTime: "11:15", endTime: "12:00", coverRelevant: true },
  { id: "L6A", label: "Lesson 6A", dayOrder: 7, startTime: "12:00", endTime: "12:45", coverRelevant: true },
  { id: "L6B", label: "Lesson 6B", dayOrder: 8, startTime: "12:45", endTime: "13:30", coverRelevant: true },
  { id: "L7", label: "Lesson 7", dayOrder: 9, startTime: "13:30", endTime: "14:15", coverRelevant: true },
  { id: "L8", label: "Lesson 8", dayOrder: 10, startTime: "14:15", endTime: "15:00", coverRelevant: true },
  { id: "CCA", label: "CCA", dayOrder: 11, startTime: "15:05", endTime: "16:00", coverRelevant: true },
];

export const protectedCommitmentCodes: CommitmentCode[] = [
  "SLT",
  "SEN",
  "PLM",
  "STM",
  "MTM",
  "ETM",
  "ASM",
  "B2 DR",
].map((code) => ({
  code,
  label: code === "B2 DR" ? "Building 2 directed responsibility" : `${code} meeting`,
  category: "MEETING",
  coverEligible: false,
  protected: true,
}));

export const vacantPosts = [
  { id: "post-arabic-1", name: "Arabic 1", status: "VACANT", phase: "CROSS_PHASE", roleType: "SPECIALIST_TEACHER", subject: "Arabic" },
  { id: "post-arabic-2", name: "Arabic 2", status: "VACANT", phase: "CROSS_PHASE", roleType: "SPECIALIST_TEACHER", subject: "Arabic" },
  { id: "post-arabic-hod", name: "Arabic HOD", status: "VACANT", phase: "CROSS_PHASE", roleType: "LEADERSHIP", subject: "Arabic" },
  { id: "post-arabic-ls", name: "Arabic LS", status: "VACANT", phase: "CROSS_PHASE", roleType: "SUPPORT", subject: "Arabic" },
] as const;

export const people: Person[] = [
  {
    id: "paul-hughes",
    firstName: "Paul",
    lastName: "Hughes",
    displayName: "Mr Paul Hughes",
    active: true,
    phase: "SECONDARY",
    roleType: "SPECIALIST_TEACHER",
    subjects: ["Computing"],
    coverEligible: true,
    coverPriority: "NORMAL",
    registrationGroupId: null,
  },
  {
    id: "hina-khan",
    firstName: "Hina",
    lastName: "Khan",
    displayName: "Mrs Hina Khan",
    active: true,
    phase: "SECONDARY",
    roleType: "LEADERSHIP",
    subjects: ["Maths"],
    coverEligible: true,
    coverPriority: "LOW",
    registrationGroupId: "7B",
  },
  {
    id: "crispin-cole",
    firstName: "Crispin",
    lastName: "Cole",
    displayName: "Mr Crispin Cole",
    active: true,
    phase: "SECONDARY",
    roleType: "LEADERSHIP",
    subjects: ["Drama"],
    coverEligible: true,
    coverPriority: "LOW",
    registrationGroupId: null,
  },
  {
    id: "eyfs-cover-example",
    firstName: "EYFS",
    lastName: "Teacher",
    displayName: "EYFS Teacher",
    active: true,
    phase: "EYFS",
    roleType: "EYFS_CLASS_TEACHER",
    subjects: ["EYFS"],
    coverEligible: true,
    coverPriority: "NORMAL",
    registrationGroupId: "EYFS-A",
  },
  {
    id: "primary-cover-example",
    firstName: "Primary",
    lastName: "Teacher",
    displayName: "Primary Teacher",
    active: true,
    phase: "PRIMARY",
    roleType: "PRIMARY_CLASS_TEACHER",
    subjects: ["Primary"],
    coverEligible: true,
    coverPriority: "NORMAL",
    registrationGroupId: "Y5-A",
  },
];

export const teachingEvents: TeachingEvent[] = [
  {
    id: "y9-comp-g1-tu-l1",
    subject: "Computing",
    classCodes: ["Year 9A"],
    yearGroup: "9",
    groupCode: "Group 1",
    room: "Computing Lab (Building 2)",
    assignedPersonIds: ["paul-hughes"],
  },
  {
    id: "y9-comp-g2-tu-l1",
    subject: "Computing",
    classCodes: ["Year 9A"],
    yearGroup: "9",
    groupCode: "Group 2",
    room: "Computing Lab (Building 2)",
    assignedPersonIds: ["sample-set-teacher"],
  },
  {
    id: "y7-pe-multi-mo-l2",
    subject: "PE",
    classCodes: ["Year 7A", "Year 7B"],
    yearGroup: "7",
    room: "Sports Hall",
    assignedPersonIds: ["paul-hughes", "crispin-cole"],
  },
];

export const timetableEntries: TimetableEntry[] = [
  {
    id: "paul-tu-l1-comp",
    day: "TUESDAY",
    periodId: "L1",
    personId: "paul-hughes",
    teachingEventId: "y9-comp-g1-tu-l1",
    subject: "Computing",
    classCodes: ["Year 9A"],
    groupCode: "Group 1",
    status: "TEACHING",
    room: "Computing Lab (Building 2)",
    sourceText: "Extracted from Staff 26Aug.pdf page: Mr Paul Hughes",
  },
  {
    id: "paul-tu-l2-comp",
    day: "TUESDAY",
    periodId: "L2",
    personId: "paul-hughes",
    subject: "Computing",
    classCodes: ["Year 8A"],
    status: "TEACHING",
    room: "Computing Lab (Building 2)",
  },
  {
    id: "paul-tu-l3-comp",
    day: "TUESDAY",
    periodId: "L3",
    personId: "paul-hughes",
    subject: "Computing",
    classCodes: ["Year 7C"],
    status: "TEACHING",
    room: "Computing Lab (Building 2)",
  },
  {
    id: "paul-tu-l4-comp",
    day: "TUESDAY",
    periodId: "L4",
    personId: "paul-hughes",
    subject: "Computing",
    classCodes: ["Year 7B"],
    status: "TEACHING",
    room: "Computing Lab (Building 2)",
  },
  {
    id: "paul-tu-cca-slt",
    day: "TUESDAY",
    periodId: "CCA",
    personId: "paul-hughes",
    classCodes: [],
    commitmentCode: "SLT",
    status: "MEETING",
    sourceText: "SLT",
  },
  {
    id: "hina-tu-reg",
    day: "TUESDAY",
    periodId: "REG",
    personId: "hina-khan",
    classCodes: ["7B"],
    status: "REGISTRATION",
  },
  {
    id: "hina-tu-cca-slt",
    day: "TUESDAY",
    periodId: "CCA",
    personId: "hina-khan",
    classCodes: [],
    commitmentCode: "SLT",
    status: "MEETING",
  },
  {
    id: "eyfs-l5-lunch",
    day: "TUESDAY",
    periodId: "L5",
    personId: "eyfs-cover-example",
    classCodes: ["EYFS"],
    status: "LUNCH",
    sourceText: "Operational EYFS working lunch rule",
  },
];

export const lunchAllocations: LunchAllocation[] = [
  { personId: "eyfs-cover-example", day: "TUESDAY", periodId: "L5", source: "ROLE_RULE", notes: "EYFS working lunch" },
  { personId: "primary-cover-example", day: "TUESDAY", periodId: "L6A", source: "ROLE_RULE", notes: "Years 1-6 lunch starts at 12:00" },
  { personId: "primary-cover-example", day: "TUESDAY", periodId: "L6B", source: "ROLE_RULE", notes: "Primary lunch protected until 13:00" },
  { personId: "paul-hughes", day: "TUESDAY", periodId: "L6B", source: "ADMIN", notes: "Specialist lunch requires admin confirmation" },
];

export const existingCover: CoverAssignmentSnapshot[] = [
  {
    absentPersonId: "someone-else",
    coveringPersonId: "crispin-cole",
    date: "2026-08-26",
    day: "TUESDAY",
    periodId: "L2",
    status: "COVERED",
  },
];

export const coverLoads: Record<string, CoverLoad> = {
  "paul-hughes": { today: 0, week: 1, term: 2, minutes: 90 },
  "hina-khan": { today: 0, week: 2, term: 5, minutes: 225 },
  "crispin-cole": { today: 1, week: 3, term: 6, minutes: 270 },
  "eyfs-cover-example": { today: 0, week: 0, term: 1, minutes: 45 },
  "primary-cover-example": { today: 0, week: 0, term: 0, minutes: 0 },
};
